### ISSUE TITLE
Check-in .proto as part of generated python and go SDK

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi#112]
There's been a feedback on availing .proto file (used to generate protobuf stubs) as part of gosnappi itself.
Need to confirm following:
- Where exactly to check-in .proto ? In the parent repository or as part of generated python or go SDK ?
- Why does the user intend to use .proto ? Do they want the internal protobuf stubs to be generated in a certain way ?

**Comment by shubh90** [comment]
Why does the user intend to use .proto ? Do they want the internal protobuf stubs to be generated in a certain way ?
> In order to use the code inside google we need to import it into google third_party. We would generate the code from the imported .proto file. We prefer generating proto files on demand else we cannot ensure that the generated code works with the all the proto utilities and proto runtime in google3.

**Comment by ashutshkumr** [comment]
@shubh90 gosnappi includes following:
- protobuf stubs: https://github.com/open-traffic-generator/snappi/tree/main/gosnappi/snappipb
- wrapper above protobuf stubs: https://github.com/open-traffic-generator/snappi/blob/main/gosnappi/gosnappi.go

So to effectively use gosnappi with your own set of protobuf stubs, here's what you'll need to do:
- either git clone the entire repo or `go get` gosnappi or download tarred gosnappi from release link (this one doesn't exist but we can provide if needed)
- remove snappipb/* and generate your own with .proto provided
- to generate, ensure package names and other generation options are equivalent to what gosnappi expects. https://github.com/open-traffic-generator/openapiart/blob/main/openapiart/openapiart.py#L179

**Comment by Rangababu-R** [comment]
.proto file is made available from the artifacts. If it doesn't satisfy the use case feel free to reopen the issue

**Comment by ashutshkumr** [comment]
Path to .proto: https://github.com/open-traffic-generator/snappi/releases/download/v0.6.16/otg.proto

where v0.6.16 can be replaced with any snappi release.
