### ISSUE TITLE
GoSnappi: Need access to api GrpcClient 

### ISSUE THREAD

**Issue by rudranil-das** [open-traffic-generator/snappi#134]
Use case: We would like to replace grpc calls to protocol-engine (currently via otg_grpc_pb.go) by gosnappi in ixia-c controller implementation.

The issue is grpc-Client in gosnappiApi is a private member with no public accessible APIs

```
type gosnappiApi struct {
	api
	grpcClient snappipb.OpenapiClient
	httpClient httpClient
}
```

It would be help if api.grpcClient is exposed through a new/get hook on gosnappiApi so that further API calls (SetConfig/SetProtocolState/...) using this client could be made; e.g. 
```
gosnappi.NewApi().GetGrpcClient().SetConfig(...)
```

**Comment by rudranil-das** [comment]
To support the use case, we would need the following:
1. grpcConnect to be available as public (or equivalent)
2. something like GetGrpcClient which would return api.grpcClient.

**Comment by ashutshkumr** [comment]
Checked with @rudranil-das further on the usecase. Existing functionality (`NewGrpcTransport()`) should suffice.
