### ISSUE TITLE
gosnappi: Deserialization of negative value for metrics 

### ISSUE THREAD

**Issue by indraniBh** [open-traffic-generator/snappi#135]
When controller sends negative value got following error:
"property bytes_tx shall be of type <class 'int'> at <class 'snappi.snappi.PortMetric'> \n got -2135387776 of type <class 'int'> "

gosnappi should deserialize negative value.

**Comment by ANISH-GOTTAPU** [comment]
@indraniBh : didn't get the use case, why the controller sends negative value for bytes_tx, can you please elaborate

**Comment by indraniBh** [comment]
@ANISH-GOTTAPU : Currently SetBytesTx(value int32) takes int32.
From usstream we are receiving bytes_tx as int64 and then typecast it to int32().
For lower value it works fine.
For higher values of bytes_tx like 2151114560 > range of int32, it takes garbage value (negative value).

**Comment by ANISH-GOTTAPU** [comment]
closing the issue related https://github.com/open-traffic-generator/models/issues/188 , re-open if issue exists after the models update
