### ISSUE TITLE
For a given .proto file, gosnappi client and gRPC server in non-go language may not always be compatible

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi#137]
We have hit this issue in multiple instances. Here's the reason why:

Let's take an exampe of otg.proto. The package name is defined as `package otg;`.
- When we generate a C++ server skeleton, without any modification (in package name), we end up generating gRPC skeletons where URLs look like `/otg.Openapi/SetConfig`
- When we generate gosnappi using openapiart, we modify the package name to be used as `snappi`, moreover openapiart further appends a suffix resulting in package name `snappipb` resulting in URL that looks like `/snappipb.Openapi/SetConfig`

This results in an incompatible API call.

There are two solutions that we need to choose from:
- Ask any implementor of otg.proto to use `snappipb` as package name (or any other package name that's relevant to a given project). That's what we currently do for ixia-c gRPC server. https://github.com/open-traffic-generator/otg-grpc/blob/main/do.sh#L30
  - This may resolve the problem quickly but does not seem like a good solution (because how do we enforce this ?)
  - e.g. in this case, we didn't enforce this for ixia-c protocol-engine and ultimately we noticed the incompatibility
- Modify the generated gRPC skeleton in gosnappi to use original package name in URL. We could also put some other restriction.

**Comment by alakendu** [comment]
fix should available in  https://github.com/open-traffic-generator/snappi/releases/tag/v0.6.16
