### ISSUE TITLE
gosnappi BGP `as_number` field uses signed int32 - not enough for 4-byte ASN value range

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/snappi#195]
4-byte BGP ASN must accept values in the range from `0` to `2^32-1` (https://www.arin.net/resources/guide/asn/)
This requires use if `uint32` to represent ASNs, not `int32` currently in use by gosnappi. Using `int32` leads to the values from `2^31-1` to `2^32-1` to be negative.

**Comment by apratimmukherjee** [comment]
Plan is to fix this as part of data refactor with modification of format to new option available uint32 ( https://jira.it.keysight.com/browse/ATHENAG-474 )

**Comment by bortok** [comment]
Confirming as fixed in v0.12 with migration to unsigned int32
