### ISSUE TITLE
Update grpc-tools to support Python 3.12

### ISSUE THREAD

**Issue by bluecmd** [open-traffic-generator/snappi#219]
Hi,

I am running Fedora 39 and it uses Python 3.12. The package `grpc-tools` introduced support for Python 3.12 in version 1.59.0, see [this](https://github.com/grpc/grpc/commit/ffdb58dd5f938eb6fec3073c9fb7ec81870d76d6) commit.

I would appreciate if you could consider upgrading the `grpc-tools` package so I can use it, thanks!

**Comment by arkajyoti-cloud** [comment]
We are looking into it right now.

**Comment by biplamal** [comment]
Support is added in snappi v1.1.1
