### ISSUE TITLE
Add support for Get extended community link bandwidth in snappi

### ISSUE THREAD

**Issue by sunilprgit** [open-traffic-generator/snappi#220]
AS per below OTG API reference i see the path is mentioned but get extended community link bandwidth is not supported in snappi
request to add support for getting extended community link bandwidth value.

devices->bgp->ipv_interfaces->peers->v4_routes->extended_communities 
in https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/master/artifacts/openapi.yaml&nocors

**Comment by apratimmukherjee** [comment]
Feature is now available in https://github.com/open-traffic-generator/ixia-c/releases/tag/v1.4.0-1
