### ISSUE TITLE
need more control over packet_count of a flow

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/snappi#48]
FYI, I have not tested this in snappi, issue found with tgen, assuming implementation is the same.

If you have a traffic item with 16 flow groups and configure the tgen.flow to run until 10k packets are sent ( duration=Duration(FixedPackets(packets=packet_count) ) the traffic item is actually set to have 'Fixed Packet Count' 625 (10k/16 flow groups). This is fine for the scenario where the user wants a total of 10k packets sent no matter the flows/ports.

But we need to consider the scenario where the user actually wants to know how many packets it will be sending per port (which I believe will be more common). This user would expect that when setting packet_count=10k, he will see 10k per traffic item (and from that he could determine per port distribution). Right now this user would have to do the reverse math: if I want to send 10k per flow group, then I need to configure tgen to send 10K x flow groups...

So to overcome this, instead of having tgen silently doing the math, it should take the packet_count as is, and expose a setting for frame count distribution (and let the user decide how to split this count among flow groups).

**Comment by ajbalogh** [comment]
The intent of the models is that a user specifies a packet count per flow. This means if there is one flow and a packet count of 100 packets that is exactly what will be sent out - it is an aggregate.  
There is no concept of traffic items, flow groups etc as those are implementation specific.
