### ISSUE TITLE
docs sample uses obsolete methods https://github.com/open-traffic-generator/snappi/blob/main/docs/e2e_port_flow_config.py#L79

### ISSUE THREAD

**Issue by dgalan-xxia** [open-traffic-generator/snappi#56]
the methods used to get stats in https://github.com/open-traffic-generator/snappi/blob/main/docs/e2e_port_flow_config.py#L79 are no longer available on a snappi.Api object. Please update accordingly

**Comment by ANISH-GOTTAPU** [comment]
stale issue
