### ISSUE TITLE
Specify standard issue template to be used throughout all repositories in open-traffic-generator

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi#6]
An issue template should include at least following:
- Working python, API and OS version
- Failing python, API and OS version
- Testbed details (TBD)
- Example snippet or script that reproduces the issue
- Error stack or failure message
- Always reproducible or not

This needs more discussion. Will revisit after attaining snappi readiness.

**Comment by ANISH-GOTTAPU** [comment]
issue template added
