### ISSUE TITLE
ENH:SnappiIter.append(item) should return item

### ISSUE THREAD

**Issue by chrispsommers** [open-traffic-generator/snappi#64]
Examples I've seen create multiple flow objects like this, for example:
```
flow1, flow2 = self.cfg.flows.flow(name='f1').flow(name='f2')
```
However, it can be useful to allow one-at-a-time flow creation, especially for programmatic flow creation using loops where the number of flows cannot be hardcoded. For example,
```
flow2=snappi.Flow(name='f2')
self.cfg.flows.append(flow2)
```
If `append()` returned `item` you could do this which is much more compact and costs nothing.
```
flow2 = self.cfg.flows.append(snappi.Flow(name='f2'))
```

**Comment by ajbalogh** [comment]
one at a time flow creation, compact one liner and no need for additional import
```python
flow1, = api.config().flows.flow(name='f1')
```

**Comment by chrispsommers** [comment]
I understand the form, but when I tried to add a second flow:
```
flow2, = self.cfg.flows.flow(name='f2')
```
I got "Too many values to unpack, expected 2, got 1"

**Comment by ajbalogh** [comment]
unpacking requires placeholders for all items, in the case where its not being provided the second syntax would be used
```python
flow1 = api.config().flows.flow(name='f1')[-1]
```

**Comment by chrispsommers** [comment]
OK, I'll change my issue to say that the examples ought to show more use-cases of creating flows in separate lines using the `[-1]` form, as opposed to creating say 2 at once with the cascaded flow creation, or creating the first flow with the `flow1, =` form. It's very clever and Pythonic, but the implications of returning an iterator as the result is not really obvious. Also, you can't just cut and paste code to "make more flows." Starting with
```
flow1, = api.config().flows.flow(name='f1')
```
You can't do this:
```
flow2, = api.config().flows.flow(name='f2') # Too many values to unpack
```
You can do this as second step:
```
flow2 = api.config().flows.flow(name='f2')
```
But what you get back isn't a flow, it's the iterator, so later on when you try to set properties you get errors. So from an examples point of view, I think it'd be in reader's interests to see this form
```
flow1 = api.config().flows.flow(name='f1')[-1]
```
more often than this form
```
flow1, = api.config().flows.flow(name='f1')
```
which can lead one down the wrong path if you "copy and paste" to add more flows. Just sayin'.
