### ISSUE TITLE
States are missing for control operations in gosnappi

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/snappi#93]
![image](https://user-images.githubusercontent.com/48308607/130627516-6d4b1840-91c6-433b-aca3-1700f8bf857a.png)

type TransmitState interface {
	msg() *snappipb.TransmitState
	ToYaml() string
	ToJson() string
	FromYaml(value string) error
	FromJson(value string) error
	FlowNames() []string
	SetFlowNames(value []string) TransmitState
}

State is missing

**Comment by ajbalogh** [comment]
Its present in require github.com/open-traffic-generator/snappi/gosnappi v0.4.34

```go
	txState := api.NewTransmitState().SetState(snappi.TransmitStateState.START)
```
